apiVersion: v1
kind: Service
metadata:
  name: tattle-debug
  labels:
    app.kubernetes.io/name: tattle-debug
spec:
  selector:
    app.kubernetes.io/name: tattle-debug
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
